# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='depends',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Task'),
        ),
    ]
